# -*- coding: utf-8 -*-
"""#6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KVTqbyU-aEKDHhqjz7CQe6R_kkkmlu5x

#question 6
Generate the two-mode distribution using a mixture of Gaussians. Let's assume that the first mode has mean = 2, standard deviation = 0.5, and weight = 0.6, while the second mode has mean = 5, standard deviation = 1, and weight = 0.4. We can generate this distribution using the following code:
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

# Define the parameters for the two Gaussian components
mu1, sigma1, weight1 = 2, 0.5, 0.6
mu2, sigma2, weight2 = 5, 1, 0.4

# Generate random samples from the mixture of Gaussians
n_samples = 10000
samples1 = np.random.normal(mu1, sigma1, size=int(n_samples*weight1))
samples2 = np.random.normal(mu2, sigma2, size=int(n_samples*weight2))
samples = np.concatenate([samples1, samples2])

# Plot the histogram of the samples
plt.hist(samples, bins=50, density=True, alpha=0.6)

# Plot the PDF of the mixture of Gaussians
x = np.linspace(np.min(samples), np.max(samples), 100)
pdf1 = norm.pdf(x, mu1, sigma1)
pdf2 = norm.pdf(x, mu2, sigma2)
pdf = weight1 * pdf1 + weight2 * pdf2
plt.plot(x, pdf, 'r', linewidth=2)

plt.xlabel('x')
plt.ylabel('Probability density')
plt.title('Mixture of Gaussians')
plt.legend(['PDF', 'Histogram'])
plt.show()